#' PICRUST analyses
#' Based on data generated by Annelies Geirnart \\@ ETH Zurich
#' 
#' Here we will load the data for level 3 pathways, and produce a plot based on the samples we have.
#' 
# libraries and functions ----
library(readxl)
library(tidyverse)

# Load data ----
l3picrust <- read.delim(file = "data/picrust_data/genes_functions_l3.biom.txt",
                        header = FALSE,
                        comment.char = "#")

colnames(l3picrust) <- c("pathway_name",
                          "CL.10",
                          "CL.12",
                          "CL.4",
                          "CL.6",
                          "CL.8",
                          "MSQ4.AG.009",
                          "MSQ4.AG.010",
                          "MSQ4.AG.011",
                          "MSQ6.AG.479",
                          "MSQ6.AG.480",
                          "MSQ6.AG.481")

sample_data <- read_xlsx("data/picrust_data/mapping_alessio_excel.xlsx")


# data matrix
dm <- l3picrust[, 2:ncol(l3picrust)]
dm <- as.matrix(dm)
qn_dm <- preprocessCore::normalize.quantiles(as.matrix(dm)) #<-- quantile normalization of data
nix <- which(rowSums(dm) == 0)

mids <- 6:11
hids <- 1:5

# frequencies of "reads", sample wide
rfreq <- apply(dm, 2, function(x) x/sum(x))

freq_mat <- matrix(0, nrow = nrow(rfreq), ncol = ncol(rfreq))
for (i in seq(1, ncol(rfreq))) {
  freq_mat[which(rfreq[, i] > 0.005), i] <- 1
}

gph <- which(rowSums(freq_mat[, hids]) > ceiling(0.51 * length(hids)))
gpm <- which(rowSums(freq_mat[, mids]) > ceiling(0.51 * length(mids)))

# pathways based on organism
s1 <- rowSums(dm[, 1:5])
s2 <- rowSums(dm[, 6:11])

m1 <- rowMeans(dm[, 1:5])
m2 <- rowMeans(dm[, 6:11])

p1 <- apply(dm[, 1:5], 1, function(x) length(which(x != 0))) # <-- keep the ones that are present in most samples for organism
p2 <- apply(dm[, 6:11], 1, function(x) length(which(x != 0)))
p1 <- which(p1 > ceiling(0.51 * 5))
p2 <- which(p2 > ceiling(0.51 * 6))

# pathways only in mouse
mpath <- Reduce(intersect, list(which(s2 != 0), which(m2 > 10), p2, which(s1 == 0)))

# pathways only present in human samples
hpath <- Reduce(intersect, list(which(s1 != 0), which(m1 > 10), p1, which(s2 == 0)))

org_spec <- integer(length = nrow(dm))
org_spec[mpath] <- 1
org_spec[hpath] <- 1

# do t-test on human vs mouse
# nix <- which(rowSums(dm) == 0)
# tt_1 <- apply(dm, 1, function(x) t.test(x[1:5], x[6:11], alternative = "two.sided", paired = FALSE, var.equal = FALSE)$p.value)
# tt_2 <- apply(qn_dm, 1, function(x) t.test(x[1:5], x[6:11], alternative = "two.sided", paired = FALSE, var.equal = FALSE)$p.value)
# if (length(nix) != 0) {
#   tt_1[nix] <- 1
#   tt_2[nix] <- 1
# }
# tt <- p.adjust(tt, method = "fdr")
# sp <- integer(length(tt))
# sp[tt < 0.005] <- 1


# fc <- apply(dm, 1, function(x) mean(x[1:5])/mean(x[6:11]))
# if (length(nix) != 0) {
#   fc[nix] <- 1
# }
# sp <- integer(length(tt))
# sp[tt < 0.005 & abs(log2(fc)) > 1] <- 1


# fold change of picrust data using deseq2
library(DESeq2)

dds <- DESeqDataSetFromMatrix(countData = dm,
                              colData = sample_data,
                              design = ~ Type)

dds <- DESeq(object = dds)

mga <- results(dds,
               contrast = c("Type", "Mouse", "Human"),
               pAdjustMethod = "fdr",
               cooksCutoff = FALSE)

nix <- which(rowSums(dm) == 0)
sp <- integer(length = nrow(dm))
sp[which(mga$padj < 0.01 & abs(mga$log2FoldChange) > 1)] <- 1



# put picrust data into data frame ----
df <- data_frame(pathway_name = rep(l3picrust$pathway_name, (ncol(l3picrust) - 1)),
                 data = as.vector(as.matrix(dm)),
                 sample_name = as.vector(sapply(colnames(dm), rep, nrow(dm))),
                 sample_type = c(rep("human", 5 * nrow(dm)),
                                 rep("mouse", 6 * nrow(dm))),
                 show_pathway = rep(sp, ncol(dm)),
                 organism_specific = rep(org_spec, ncol(dm)))

# plot these things
df %>% 
  dplyr::filter(., show_pathway == 1, organism_specific == 0) %>%
  ggplot() + 
  geom_boxplot(aes(x = pathway_name, y = log2(data), fill = sample_type)) + 
  # facet_grid(~ sample_type, scales = "free") + 
  coord_flip() + 
  theme_bw() + 
  theme(panel.grid = element_blank())